Todo items - model, DB seeding and connection with User
AleksandarSavic95/todo-backend pull request #1
Opened 2018-11-13 11:44 UTC by AleksandarSavic95

2018-11-13 12:00 UTC, calico-anne requested changes

2018-11-13 12:00 UTC, calico-anne commented on database/migrations/2018_11_13_104137_create_todo_items_table.php
> +            Schema::dropIfExsists('todo_items');
`dropIfExists` :D

2018-11-13 12:00 UTC, volkova229 commented on database/seeds/TodoItemsTableSeeder.php
> +                'priority' => 0,
Kad vec imas onu Priority klasu, mozda bi mogao ovde da randomizujes to

2018-11-13 12:24 UTC, AleksandarSavic95 commented on database/migrations/2018_11_13_104137_create_todo_items_table.php
> +            Schema::dropIfExsists('todo_items');
To da ne izbacuje grešku ako ne postoji tabela (evo ovdje pitanje i odgovor - [drop vs dropIfExists](https://github.com/laravel/ideas/issues/255) :) )

2018-11-13 12:45 UTC, AleksandarSavic95 reviewed
`dropIfExists` sam ostavio (objašnjenje u komentaru), a Priority sam randomizovao kako si rekla :)

2018-11-14 08:26 UTC, calico-anne approved these changes

2018-11-14 08:26 UTC, merged